# Generated by Django 2.1.7 on 2019-04-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='yype_id',
            new_name='type_id',
        ),
    ]
