# Generated by Django 2.1.7 on 2019-04-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0002_purchase_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item_id',
        ),
    ]
