# Generated by Django 2.1.7 on 2019-04-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0002_auto_20190409_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item_id',
        ),
    ]
