# Generated by Django 2.1.7 on 2019-04-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0003_remove_purchase_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv_manage.Item'),
            preserve_default=False,
        ),
    ]
