# Generated by Django 2.1.7 on 2019-04-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0003_remove_purchase_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitemlink',
            name='items_id',
        ),
        migrations.RemoveField(
            model_name='purchaseitemlink',
            name='purchase_id',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_manage.Attributes'),
        ),
        migrations.DeleteModel(
            name='PurchaseItemLink',
        ),
    ]
