# Generated by Django 2.1.7 on 2019-04-12 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0004_auto_20190409_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_manage.Item')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_manage.Purchase')),
            ],
        ),
    ]
